version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - S3_ACCESS_KEY=YOUR_ACCESS_KEY
      - S3_SECRET_KEY=YOUR_SECRET_KEY
    command: ./wait-for-postgres.sh db ./augventure-app
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:3000