port: "8000"

db:
  host: "localhost"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

s3:
  bucketName: "augventure"
  region: "ru-central1"
  endpoint: "https://storage.yandexcloud.net"